### ISSUE TITLE
Gives "Fail to launch the browser process error" if chrome is already open. Works only if chrome is closed at launch time

### ISSUE THREAD

**Issue by SarthakChaudhary** [lanly-dev/VSCode-LMPTM#10]
OS: Windows
Issue with this method is that chrome closes when I close vscode. I have recently formatted my pc and it worked before, I'm not sure what changed
![image](https://user-images.githubusercontent.com/30460304/114768111-15b08300-9d86-11eb-9326-7de7373b8a69.png)

**Comment by lanly-dev** [comment]
The Chrome window that launched from the VS Code window closes when the same VS Code window closed - This is an expected behavior unless I misunderstood your issue. For the screenshot above, not sure how you get that but I suspect something wrong with your path. How about trying to change the `User Data` to `User-Data`? - Sometimes, a space in the name could cause problems or try to pick a different directory.

**Comment by SarthakChaudhary** [comment]
You understood the issue correctly only. Also using "User-Data" instead of "User Data" gives me the same result as I would get from putting in some random string. I doubt there's an issue with the path cus wrong path opens a window and immediately closes it while the correct path opens about:blank and shows "Chrome is being controlled by automated test software" while also giving the above errors

**Comment by lanly-dev** [comment]
Okay, look like the path you put there is the official path for Chrome to store its default profile. I have never tried to put my Chrome default path in there since if you don't specify it, I think it will use the default profile anyway, does it?. That error looks like there is conflicting access between two instances of Chrome like this one said `https://github.com/puppeteer/puppeteer/issues/4261#issuecomment-607862797`. How about trying to put user data somewhere else like in the document folder? Not sure why it worked before as you said.
Update: I see, you are trying to use your same default profile. As for my case, I try to use 2 separated user data. I'm not really sure how to solve those conflicts. How about trying to copy your default user data and put it somewhere else and make LMPTM point to it?

**Comment by SarthakChaudhary** [comment]
I tried that and while it works, it's a bother as it doesn't have any of my preferences for extensions somehow and is basically treated like a new user with the same extensions. I can't merge the tabs for the two and I don't want to have an extra window open. Also, it too closes when VSCode is closed. Lastly, there is another issue where when I close VSCode and chrome closes as well, the next time I try to open chrome using Launch from vscode it opens and closes immediately. This keeps up until I open that profile without using vscode and I don't know how to do this for userdata stored somewhere other than default location.

I also looked up the link and the error and realized how simple the error is. The extension uses GPUCache for some reason and while chrome is running it cannot make whatever changes it needs to make as Windows doesn't let you work on files that are already open. I have no idea how it worked before. I wonder if there's a setting for using GPUCache that I had turned off before which is on now. I turned off hardware acceleration as that's the first thing that came to mind but that didn't work. Turning off cache completely might work, I'd try that after my exams are over. 

From the code side, this issue can be solved by either not using GPUCache somehow or keeping chrome open after VSCode is closed. I have no idea how feasible these solutions are.

**Comment by lanly-dev** [comment]
Weird, I expected you will get the same preferences if you clone your data, I guess not. It is interesting to know that it can't transfer tabs between those 2 Chrome instances.
I don't think I have had a case that when vscode closes and Chrome (that launched from the very vscode instance) doesn't - unless the connection between those 2 somehow broke. From my understanding, when you launch Chrome using Puppeteer, it is a spawned child process. If the main process exits, which is the vscode instance, the child process also exits. I bet there a way to detach the child process from that main process, but then the new vscode instance need to get some saved reference to connect the already launched Chrome instance - if you want to control it.
I'm not sure about GPUCache, but if your extension requires it, and then you disable it - there is a good chance that could make the Chrome's extension stops working properly.
Good luck on you exams.

**Comment by SarthakChaudhary** [comment]
I guess there is not much we can do here, can we? I'll close the issue ig. Thanks ^^
