### ISSUE TITLE
Doesn't work with videos on drive

### ISSUE THREAD

**Issue by SarthakChaudhary** [lanly-dev/VSCode-LMPTM#11]
Break Blade Movie 1.mkv :
https://drive.google.com/file/d/1u4jH2N39QMd6rSGnfeMBA6mzuDq8Q7EO/view
This is a public video I found which can be used for verifying that it indeed does not work for drive videos. I thought they would cus videos on drive have a youtube video interface. If possible implement this feature please, it'll be a great help with my online classes.

**Comment by lanly-dev** [comment]
Indeed, I would be surprised if it does work for Google Drive video or anything other than those 4 music streaming websites (3 to be correct since Spotify already changed their UI so that is why it doesn't work anymore). Implementing this feature kinda out of scope for "Music". You could argue with the extra use-case for Youtube that I put in the readme, but it just happens that Youtube is already supported.
I could implement this feature if I have time - it will be a while and no telling if it would work. I recalled that I can't log in to my Gmail and Youtube account (it worked back then, so I bet they will be stricter in the future because of bots/automation - take a look at GPU buying bot lol) in the spawned window so I'm not sure how you able to see the private videos, is it shared link? If the video requires a login then it won't work.
Since it is a Google drive video then you could download it? There is an extension to control VLC player could be an alternative solution.

**Comment by SarthakChaudhary** [comment]
The link I put up is open for everyone who is logged in. It requires a login like youtube does but since I'm already logged in I'm not sure if it would be a problem. The pick option does show up for gdrive but it says sorry or something like that when I click it. I'll close the issue since it has been brought to your notice and I don't want to push you into working towards it if you're already busy

**Comment by lanly-dev** [comment]
Interesting, I was able to view the video about 2 days ago without asking for access, now it does, strange! Yeah, I don't use the default user data so I don't have my login saved, and I don't want to have those 2 of the chromes' information mix up. I could point my normal Chrome to do log in to save my login information in my LMPTM's user data folder, but it is kinda inconvenient. Therefore, your case wouldn't work in my situation unless I could bypass bot filtering from those sites.
The extension script check for the URL to filter which one is which so it won't work for other websites.
Thank you for posting the issue.
