### ISSUE TITLE
Error: The process <Insert Browser PID> not found

### ISSUE THREAD

**Issue by cubuzz** [lanly-dev/VSCode-LMPTM#5]
After the latest fix for Chromium, I am now experiencing this problem.
Apparently when launching the browser something goes wrong with hooking into it.
The message prompt says "read ECONNRESET" (afaik that means "IO Error: Connection reset by remote host"), and the console also outputs  "ERROR: The process <ID> not found".

![image](https://user-images.githubusercontent.com/30159582/72662562-e9724f00-39e8-11ea-8628-580961b73b7e.png)

**Comment by cubuzz** [comment]
![image](https://user-images.githubusercontent.com/30159582/72662591-37875280-39e9-11ea-8709-1b53ff85487c.png)

**Comment by cubuzz** [comment]
Verbose output:
![image](https://user-images.githubusercontent.com/30159582/72662621-6dc4d200-39e9-11ea-99ae-659e0110bf44.png)

**Comment by lanly-dev** [comment]
So which os are you using Chromium on?

**Comment by cubuzz** [comment]
Windows 10 Pro x64, and I'm running the Brave browser based on Chromium.

**Comment by lanly-dev** [comment]
Strange, it was working before, this looks like in the same situation the one on MintOS that you mentioned before. Probably Brave updated something.

**Comment by lanly-dev** [comment]
Luckily, I found [--disable-sync](https://peter.sh/experiments/chromium-command-line-switches), puppeteer uses it in its default setting, that prevents to launch Brave, not sure why Brave doesn't work with this flag since it  "disables syncing browser data to a Google Account."  🤔. I updated the extension so you will see `lmptm.ignoreDisableSync` option. Enable that option will help you to launch Brave.
