### ISSUE TITLE
SoundCloud login issue

### ISSUE THREAD

**Issue by rhapsodic-numrod** [lanly-dev/VSCode-LMPTM#6]
When you try to login to SoundCloud it does not let you in because it thinks you are a robot.

**Comment by lanly-dev** [comment]
How do you log in? As for myself, I log in via Facebook login so I haven't tested it with other login methods. Could you provide the screenshot of the message?

**Comment by rhapsodic-numrod** [comment]
I log in using my email address but then I get this
![sc](https://user-images.githubusercontent.com/48629623/84580166-d4052380-add4-11ea-82f4-34b28df9a809.png)

**Comment by lanly-dev** [comment]
I did some research on this; it looks like Soundcloud is using _Distil Networks_ to prevent scraper and crawler bot, and it targets tools like the [Puppeteer](https://github.com/puppeteer/puppeteer) that I am using. [puppeteer-extra-plugin-stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) seems like a prominent solution (probably the only one for this problem). Unfortunately, the project's maintainer stops being active since January. Currently, that project doesn't have good Typescript support so I can't use it. I also tried the User-Agent generator method but it doesn't help. So far, it is a dead-end to this problem but I will keep track and fix it once when there is a solution to it.

Alternative solution:
Could you search your username in Soundcloud and listen to your playlists from there?

Related issue: `https://github.com/puppeteer/puppeteer/issues/4985`
An interesting related project: https://github.com/paulirish/headless-cat-n-mouse

**Comment by rhapsodic-numrod** [comment]
Okay, thanks. Will try the alternative.
