### ISSUE TITLE
No button for 5s forward/backward :(

### ISSUE THREAD

**Issue by 41y08h** [lanly-dev/VSCode-LMPTM#8]
Please include button for skipping 5s forward/backward .

**Comment by lanly-dev** [comment]
For me, this is kind of counterproductive. If a song distracts you, you should just skip it rather than trying by seek 5s forward/backward while programming. Also, if you are a Spotify user, it seems like they don't even have this [feature ](https://community.spotify.com/t5/Closed-Ideas/Keyboard-shortcut-to-seek-in-tracks/idi-p/22415) in keyboard shortcut which I kind of surprise. Nevertheless, having extra features is a good thing so if more people request this or you could give me a better use-case, I may consider this, and you are welcome to make a PR for this feature.

**Comment by 41y08h** [comment]
I don't know puppeteer, I'm new to testing and haven't tried automation testing till date. I was requesting about this feature to watch YouTube programming tutorials and coding along without even touching mouse, hope you understand this, if you ever followed a programming tutorial and coded along then you must have faced that problem of switching between windows with either pressing a key combination (then doing what you want with the video) or using cursor. Thanks a lot for your response 👍 😄

**Comment by lanly-dev** [comment]
Puppeteer is technically a testing tool as you said but I use it to control the browser so it is not really testing in a sense in this case.
Surprisingly, I never thought that you would use my extension to learn to code which is really creative and educational. It is definitely worth to become a useful feature. I will add it to the next update when I have the time. Thank you for the input.

**Comment by lanly-dev** [comment]
It took me a while to add the function (version 1.4.0). Hope it's still helpful!

**Comment by 41y08h** [comment]
Where's the option dude?

**Comment by lanly-dev** [comment]
![image](https://user-images.githubusercontent.com/14204732/97796665-0bcd0600-1bd2-11eb-97be-3903436b8334.png)

**Comment by gshanbhag525** [comment]
how to change the keyboard shortcuts for the commands....which file to look out for @lanly-dev

**Comment by lanly-dev** [comment]
https://github.com/lanly-dev/VSCode-LMPTM/issues/1#issuecomment-879536559
